### ISSUE TITLE
Android Basics: Collections

### ISSUE THREAD

**Issue by haraldsperre** [google-developer-training/android-basics-kotlin-words-app#59] opened 2021-03-04 07:27 UTC
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-collections?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-collections#4

**In which task and step of the codelab can this issue be found?**
Collections in Kotlin: Step 5 make word lists

**Describe the problem**
The explanation of the startsWith-method is, presumably by mistake, displayed as code. This makes it harder to read the explanation.

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![image](https://user-images.githubusercontent.com/644287/109926543-59ae6380-7cc3-11eb-804f-993f167d53d1.png)

**Comment by jtavva** [comment] 2021-03-18 00:01
Duplicate of #24 
To be published

**Closed by jtavva** 2021-03-18 00:01 UTC
Labels: duplicate
