### ISSUE TITLE
Android Basics: Fragments Navigation component

### ISSUE THREAD

**Issue by restover** [google-developer-training/android-basics-kotlin-words-app#57] opened 2021-02-26 07:26 UTC
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-fragments-navigation-component?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-fragments-navigation-component#3

**In which task and step of the codelab can this issue be found?**

![image](https://user-images.githubusercontent.com/76655411/109268053-dff32180-784d-11eb-83cb-f6e284f22c38.png)

**Describe the problem**

I think there is a mistake, and the "tools:context" of  "FrameLayout" should be "LetterListFragment" in this part. Because, above this image, you wrote "Update tools:context in fragment_letter_list.xml to .LetterListFragment" 

That's all. sorry for my poor English, and I really appreciate your support. Have a nice day!

**Comment by jtavva** [comment] 2021-03-18 00:02
Duplicate of #33

**Closed** 2021-03-18 00:02 UTC
Labels: duplicate
