### ISSUE TITLE
Android Basics: Collections

### ISSUE THREAD

**Issue by willow19** [google-developer-training/android-basics-kotlin-words-app#54] opened 2021-02-23 05:11 UTC
**URL of codelab**: https://developer.android.com/codelabs/basic-android-kotlin-training-collections?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-collections#4

**In which task and step of the codelab can this issue be found?**: 5th task, 2nd step

**Describe the problem**: The markup to hyperlink startsWith() is not rendered properly

**Steps to reproduce?**
1. Go to the URL and task, step above
2. The startsWith() hyperlink will not be displayed properly
![Screenshot from 2021-02-23 10-41-05](https://user-images.githubusercontent.com/9603417/108804579-ac04cb80-75c3-11eb-9a14-e9c917b655d4.png)

**Versions**
Not relevant

**Additional information**
Screenshot attached

**Comment by jtavva** [comment] 2021-03-17 23:27
Duplicate of #24 
To be published

**Closed by jtavva** 2021-03-17 23:27 UTC
Labels: duplicate
