### ISSUE TITLE
Android Basics: Fragments Navigation component

### ISSUE THREAD

**Issue by lopezsolerluis** [google-developer-training/android-basics-kotlin-words-app#45] opened 2021-01-28 01:03 UTC
**URL of codelab**

https://developer.android.com/codelabs/basic-android-kotlin-training-fragments-navigation-component?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-fragments-navigation-component#3

**In which task and step of the codelab can this issue be found?**

Step 4: Create Fragment and layout Files

**Describe the problem**

In the code for [fragment_letter_list.xml], it says: [ tools:context=".WordListFragment" ], but I think it should be [ tools:context=".LetterListFragment" ]

By the way, I am really enjoying the courses; they are very well written, pleasant to read and I learn a lot. :)
**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

![Captura de pantalla de 2021-01-27 21-58-24](https://user-images.githubusercontent.com/74994729/106074721-20466f00-60eb-11eb-8c82-4a3d43aebc6e.png)

**Comment by Kb-Bojang** [comment] 2021-01-28 14:04
> **URL of codelab**
> 
> https://developer.android.com/codelabs/basic-android-kotlin-training-fragments-navigation-component?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-fragments-navigation-component#3
> 
> **In which task and step of the codelab can this issue be found?**
> 
> Step 4: Create Fragment and layout Files
> 
> **Describe the problem**
> 
> In the code for [fragment_letter_list.xml], it says: [ tools:context=".WordListFragment" ], but I think it should be [ tools:context=".LetterListFragment" ]
> 
> By the way, I am really enjoying the courses; they are very well written, pleasant to read and I learn a lot. :)
> **Additional information**
> _Include screenshots if they would be useful in clarifying the problem._
> 
> ![Captura de pantalla de 2021-01-27 21-58-24](https://user-images.githubusercontent.com/74994729/106074721-20466f00-60eb-11eb-8c82-4a3d43aebc6e.png)

Thanks @lopezsolerluis, My app was crashing whenever I tried to run it on the emulator, so I deleted the project and started all over again. Then I was stuck at step 4 as it was not showing the fragments files. Thanks to your suggestion, I am able to see the right fragment files. You have saved me a very long day of hair pulling and not having even the time to eat :)

**Comment by jtavva** [comment] 2021-03-19 19:46
Duplicate of #33 
Fix to be published

**Closed by jtavva** 2021-03-19 19:46 UTC
Labels: duplicate
