### ISSUE TITLE
Android Basics: Fragments Navigation component

### ISSUE THREAD

**Issue by Joao-VPS** [google-developer-training/android-basics-kotlin-words-app#288] opened 2022-06-01 19:41 UTC
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-fragments-navigation-component?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-fragments-navigation-component#7

**In which task and step of the codelab can this issue be found?**
Step/Page 8

**Describe the problem**
There's a difference between the of the third statement in the "Use FragmentContainerView in MainActivity" paragraph and the example shown bellow. "app:navHost" attribute is described in the statement but the example showns "app:defaultNavHost". This happens in the Portuguese version of this page and may confuse other readers.

**Steps to reproduce?**
1. Go to...
2. Click on... nothing
3. See error... difference betwen the given instruction and example

**Versions**
_Android Studio version:_ none
_API version of the emulator:_ none

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![image](https://user-images.githubusercontent.com/87478340/171487885-6581315a-beb3-4d5a-bca3-4c96e8b89910.png)

Thanks for listening.

**Comment by osuleymanova** [comment] 2022-10-03 20:11
Duplicate of #250

**Closed** 2024-01-11 21:30 UTC
