### ISSUE TITLE
Android Basics: Fragments Navigation component

### ISSUE THREAD

**Issue by codewpf** [google-developer-training/android-basics-kotlin-words-app#73] opened 2021-03-17 02:40 UTC
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-fragments-navigation-component?authuser=1&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-2%3Fauthuser%3D1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-fragments-navigation-component#3

**In which task and step of the codelab can this issue be found?**
Unit 3
Introduction to the Navigation component
step 4

**Describe the problem**
In section 3, there is a code error about "Update tools:context in fragment_letter_list.xml to .LetterListFragment".
Example code does not update successfully.

**Comment by jtavva** [comment] 2021-03-17 23:12
@codewpf 
Do you mean code snippet is not correctly updated?

**Comment by danielslabo** [comment] 2021-04-11 20:49
Not the OP but I think it is a dupe of #33

**Comment by jtavva** [comment] 2021-06-10 22:21
@codewpf 
Thank you so much for reporting this issue. This is fixed and will be published soon.

**Closed by jtavva** 2021-06-10 22:21 UTC
