### ISSUE TITLE
Android Basics: Fragments Navigation component

### ISSUE THREAD

**Issue by xtedx** [google-developer-training/android-basics-kotlin-words-app#79] opened 2021-03-27 07:55 UTC
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-fragments-navigation-component?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-fragments-navigation-component#3

**In which task and step of the codelab can this issue be found?**
in task 4 step 3

**Describe the problem**
fragment_letter_list.xml should have as described in the step
    tools:context=".LetterListFragment" 
but the code says .WordListFragment like the next code.
this is simply a "copy paste and forgot to replace text" error

<img width="1276" alt="Screen Shot 2021-03-27 at 6 50 12 pm" src="https://user-images.githubusercontent.com/13181908/112714294-e26c9800-8f2d-11eb-86cc-dbe6fb7bf63d.png">

**Comment by danielslabo** [comment] 2021-04-11 18:24
Looks like duplicate of #48

**Comment by jtavva** [comment] 2021-06-10 22:28
@xtedx 
This is fixed now. Thank you for your help.

**Closed by jtavva** 2021-06-10 22:28 UTC
