### ISSUE TITLE
Android Basics: Collections

### ISSUE THREAD

**Issue by andrew-quinn** [google-developer-training/android-basics-kotlin-words-app#65] opened 2021-03-06 20:17 UTC
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-collections?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-collections#4

**In which task and step of the codelab can this issue be found?**
Task 5: Make word lists
Step 2 ("To get a collection...")

**Describe the problem**
In the very last part of step 2, there appears to be some unintentional code formatting around what should probably just be regular prose with some code formatting mixed in. The paragraph in question begins with 

> The  [`startsWith()`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.text/starts-with.html) function returns true if

**Steps to reproduce?**
1. Go to the URL provided above
2. Search for the string `The  [` (with two spaces preceding the square bracket!)
3. See the paragraph of prose formatted as code

**Versions**
N/A 

**Additional information**
Will gladly be provided if needed!

**Comment by jtavva** [comment] 2021-03-17 23:43
Duplicate of #24

**Closed by jtavva** 2021-03-17 23:43 UTC
Labels: duplicate
