### ISSUE TITLE
Android Basics: Collections - Text in codeblock - DAC redering issue

### ISSUE THREAD

**Issue by WalkingFishes** [google-developer-training/android-basics-kotlin-words-app#39] opened 2021-01-19 15:43 UTC
https://developer.android.com/codelabs/basic-android-kotlin-training-collections

In Step 2, there is a line of text that is incorrectly showing in a code box.
    The  [`startsWith()`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.text/starts-with.html) function returns true if a string starts with the specified string. You can also tell it to ignore case, so "b" will match "b" or "B".

**Steps to reproduce?**
1. Go to  the URL for this codelab
2. Find step 2
3. You will see 2 boxes after the line "2. To get a collection. . . ", the second box should be regular text and not a code box.

This is see under Mozilla Firefox for Ubuntu canonical-1.0 v 84.0.2 (64-bit)

See the attached screenshot.
![image](https://user-images.githubusercontent.com/58010612/105057287-b10db280-5a3a-11eb-9e2a-5d08eba3fea7.png)

**Comment by jtavva** [comment] 2021-03-17 23:27
Duplicate of #24 
To be published

**Closed by jtavva** 2021-03-17 23:27 UTC
Labels: DAC rendering issue, duplicate
