### ISSUE TITLE
Android Basics: Fragments Navigation component

### ISSUE THREAD

**Issue by Barath256** [google-developer-training/android-basics-kotlin-words-app#68] opened 2021-03-08 15:48 UTC
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-fragments-navigation-component?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-fragments-navigation-component#3

**In which task and step of the codelab can this issue be found?**
No.4 Create Fragment and layout file -> fragment_letter_list.xml

**Describe the problem**
Present Code :
   tools:context=".WordListFragment">

Correct Code
   tools:context=".LetterListFragment">

**Steps to reproduce?**
1. Go to... Link given above
2. Click on... Chapter 2 
3. See error... Sub-Chapter 4 ->fragment_letter_list.xml 

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by jtavva** [comment] 2021-03-17 23:18
Duplicate of #33

**Closed by jtavva** 2021-03-17 23:18 UTC
Labels: duplicate
