### ISSUE TITLE
Android Basics: Fragments Navigation component

### ISSUE THREAD

**Issue by nokyslash** [google-developer-training/android-basics-kotlin-words-app#64] opened 2021-03-06 03:29 UTC
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-fragments-navigation-component?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-fragments-navigation-component#7

**In which task and step of the codelab can this issue be found?**
Task 2, Step 8

**Describe the problem**
Inconsistencies between text and sample code

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 4.1
_API version of the emulator:_ Physical Device

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![Sin título](https://user-images.githubusercontent.com/46078334/110193501-3c33e380-7e02-11eb-9082-f05f27921306.png)

**Comment by jtavva** [comment] 2021-03-17 23:42
Duplicate of #41

**Closed by jtavva** 2021-03-17 23:42 UTC
Labels: duplicate
