### ISSUE TITLE
Android Basics: Fragments Navigation component

### ISSUE THREAD

**Issue by EPGHH** [google-developer-training/android-basics-kotlin-words-app#145] opened 2021-06-24 21:46 UTC
**URL of codelab**

**In which task and step of the codelab can this issue be found?**

In the codelab Fragments and the Navigation Component in the 
4. Create Fragment and layout Files 

**Describe the problem**

In the final part when viewing it in Spanish, an error is presented in the code for fragment_letter_list.xml since the part of the code of tools: context = ". WordListFragment" must be tools: context = ". LetterListFragment">, but only It is presented when it is read in Spanish 

**Steps to reproduce?**
1. Go to...   codelab Fragments and the Navigation Component
2. Click on...  in the Create Fragment and layout Files and change lenguage to Spanish
3. See error...  in the code for fragment_letter_list.xml

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment] 2021-11-29 23:03
Duplicate of #155, #191

**Closed** 2024-01-11 21:30 UTC
