### ISSUE TITLE
Android Basics: Fragments Navigation component

### ISSUE THREAD

**Issue by memonahmedanees** [google-developer-training/android-basics-kotlin-words-app#70] opened 2021-03-15 07:07 UTC
**URL of codelab**

**In which task and step of the codelab can this issue be found?**

**Describe the problem**

in layout fragment_letter_list.xml  mentioned  tools:context=".WordListFragment">
but should be  tools:context=".LetterListFragment"

**Steps to reproduce?**
1. Go to...  layout folder and select fragmentLetterList.xml
2. Click on... .tools:context=".WordListFragment"

3. See error... should be LetterListFragment

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by jtavva** [comment] 2021-03-17 23:16
Duplicate of #33

**Closed by jtavva** 2021-03-17 23:16 UTC
Labels: duplicate
