### ISSUE TITLE
Android Basics: Fragments Navigation component

### ISSUE THREAD

**Issue by paps-96** [google-developer-training/android-basics-kotlin-words-app#49] opened 2021-02-13 20:43 UTC
**URL of codelab**

**In which task and step of the codelab can this issue be found?**

**Describe the problem**
After the changes, the fragment layout files should look as follows.

fragment_letter_list.xml
Here it has wrong context value

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by danielslabo** [comment] 2021-04-11 18:12
Look like a duplicate of #48

**Comment by jtavva** [comment] 2021-06-10 22:31
@paps-96 
Thank you so much for reporting this issue. This is fixed and will be published soon.

**Closed by jtavva** 2021-06-10 22:31 UTC
