### ISSUE TITLE
Android Basics: Fragments Navigation component

### ISSUE THREAD

**Issue by tobidenagan** [google-developer-training/android-basics-kotlin-words-app#66] opened 2021-03-08 09:06 UTC
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-fragments-navigation-component#3

**In which task and step of the codelab can this issue be found?**
4. Create Fragment and layout Files

**Describe the problem**
The fragment layout files look after the changes.
Specifically, in the fragment_letter_list.xml,    tools:context=".WordListFragment" should be  tools:context=".LetterListFragment"

**Steps to reproduce?**
1. Go to... Fragments and the Navigation Component
2. Click on... 4. Create Fragment and layout Files
3. See error... fragment_letter_list.xml fragment layout file

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![image](https://user-images.githubusercontent.com/33653083/110299301-cb551d00-7ff5-11eb-9255-ad7ba6ae4b77.png)
![Error Figure](https://user-images.githubusercontent.com/33653083/110299432-f0e22680-7ff5-11eb-9b9d-d4a018bd04ef.PNG)

**Comment by jtavva** [comment] 2021-03-17 23:18
Duplicate of #33

**Closed by jtavva** 2021-03-17 23:18 UTC
Labels: duplicate
