### ISSUE TITLE
Android Basics: Fragments Navigation component - typo - wrong tools:context

### ISSUE THREAD

**Issue by AlexandrePlus** [google-developer-training/android-basics-kotlin-words-app#78] opened 2021-03-25 15:11 UTC
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-fragments-navigation-component#3

**In which task and step of the codelab can this issue be found?**
4. Create Fragment and layout Files > fragment_letter_list.xml 

**Describe the problem**
It is written `tools:context=".WordListFragment">` instead of `tools:context=".LetterListFragment">` (for fragment_letter_list.xml, whereas fragment_word_list.xml is ok)

**Comment by danielslabo** [comment] 2021-04-11 18:23
Looks like duplicate of #48

**Comment by jtavva** [comment] 2021-06-10 22:27
@AlexandrePlus 
Thank you so much for reporting this issue. This is fixed and will be published soon.

**Closed by jtavva** 2021-06-10 22:27 UTC
