### ISSUE TITLE
Android Basics: Fragments Navigation component

### ISSUE THREAD

**Issue by hassan0599** [google-developer-training/android-basics-kotlin-words-app#81] opened 2021-03-29 05:06 UTC
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-fragments-navigation-component?authuser=1&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-2%3Fauthuser%3D1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-fragments-navigation-component#3

**In which task and step of the codelab can this issue be found?**
Task No. 4
Step No. 3

**Describe the problem**
In the screenshot for fragment_letter_list.xml, the tools:context should =".LetterListFragment" instead of ".WordListFragment"

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![Screenshot 2021-03-29 010238](https://user-images.githubusercontent.com/61388284/112789354-e9c59b80-902a-11eb-8e5e-9fc503e75091.jpg)

**Comment by danielslabo** [comment] 2021-04-11 18:24
Duplicate of #48

**Comment by jtavva** [comment] 2021-06-10 22:26
@hassan0599 
Thank you so much for reporting this issue. This is fixed and will be published soon.

**Closed by jtavva** 2021-06-10 22:26 UTC
