### ISSUE TITLE
Android Basics: Fragments Navigation component

### ISSUE THREAD

**Issue by TheKingsident** [google-developer-training/android-basics-kotlin-words-app#55] opened 2021-02-25 23:02 UTC
**URL of codelab**
[](https://developer.android.com/codelabs/basic-android-kotlin-training-fragments-navigation-component?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-fragments-navigation-component#3)

**In which task and step of the codelab can this issue be found?**
4. Create Fragment and Layout Files

**Describe the problem**
The XML code for "**fragment_word_list.xml**" is the same code used for "**fragment_letter_list.xml**"

**Steps to reproduce?**

1. Go to... Introduction to the Navigation Component
2. Click on... Fragments and the Navigation component
3. See error...in the fourth tab to the left labelled "4. Create Fragment and Layout Files"

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![Screenshot 2021-02-25 110246](https://user-images.githubusercontent.com/77732519/109230895-e938ab80-77c5-11eb-8c07-cca3e74d0824.jpg)

**Comment by TheKingsident** [comment] 2021-02-25 23:03
Link to the codelab: https://developer.android.com/codelabs/basic-android-kotlin-training-fragments-navigation-component?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-fragments-navigation-component#3

**Comment by danielslabo** [comment] 2021-04-11 18:13
Look like duplicate of #48

**Comment by jtavva** [comment] 2021-06-10 22:30
@TheKingsident 
Thank you so much for reporting this issue. This is fixed and will be published soon.

**Closed by jtavva** 2021-06-10 22:30 UTC
