### ISSUE TITLE
Android Basics: Fragments Navigation component

### ISSUE THREAD

**Issue by namratasuryavanshi** [google-developer-training/android-basics-kotlin-words-app#50] opened 2021-02-14 00:23 UTC
**URL of codelab**
Fragments and the Navigation Component - https://developer.android.com/codelabs/basic-android-kotlin-training-fragments-navigation-component?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-fragments-navigation-component#3

**In which task and step of the codelab can this issue be found?**
THis section - 
After the changes, the fragment layout files should look as follows.
fragment_letter_list.xml

**Describe the problem**
In this file = fragment_letter_list.xml

Update
tools:context=".WordListFragment">

to
tools:context=".LetterListFragment">

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
<img width="792" alt="Screen Shot 2021-02-13 at 4 24 44 PM" src="https://user-images.githubusercontent.com/4482770/107865099-1e351d80-6e18-11eb-9d4a-13d51f705343.png">

**Comment by jtavva** [comment] 2021-03-19 19:43
Duplicate of #33 
Fix to be published

**Closed by jtavva** 2021-03-19 19:43 UTC
Labels: duplicate
