### ISSUE TITLE
Android Basics: Collections - Text in codeblock - DAC redering issue

### ISSUE THREAD

**Issue by Tremblor** [google-developer-training/android-basics-kotlin-words-app#38] opened 2021-01-16 09:47 UTC
**URL of codelab**

https://developer.android.com/codelabs/basic-android-kotlin-training-collections#4

**In which task and step of the codelab can this issue be found?**

Step 2

**Describe the problem**

The following text appears as a code block rather than regular text:
   The  [`startsWith()`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.text/starts-with.html) function returns true if a string starts with the specified string. You can also tell it to ignore case, so "b" will match "b" or "B".

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by jtavva** [comment] 2021-03-17 23:26
Duplicate of #24

**Closed by jtavva** 2021-03-17 23:26 UTC
Labels: DAC rendering issue, duplicate
