### ISSUE TITLE
Android Basics: Collections -  DAC rendering issue

### ISSUE THREAD

**Issue by MaverickAlex** [google-developer-training/android-basics-kotlin-words-app#28] opened 2021-01-06 20:11 UTC
https://developer.android.com/codelabs/basic-android-kotlin-training-collections?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-collections#4

task 5 step 2

it appears part of the page is in a code section and should just be in a text section, as it appears to be describing the 
"The  [`startsWith()`](https://kotlinlang.org/api/latest" function and has a link to the docs

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by jtavva** [comment] 2021-01-07 00:28
Duplicate of #24

**Closed by jtavva** 2021-01-07 00:28 UTC
Labels: duplicate
