### ISSUE TITLE
Android Basics: Fragments Navigation component

### ISSUE THREAD

**Issue by OutsiderCode** [google-developer-training/android-basics-kotlin-words-app#56] opened 2021-02-25 23:29 UTC
**URL of codelab**
Unit3> Fragments and the Navigation Component> 4. Create Fragment and layout Files> Step3

**In which task and step of the codelab can this issue be found?**

**Describe the problem** The step 3 says "Update tools:context in fragment_letter_list.xml to .LetterListFragment" but the image below contains "tools:context=".WordListFragment", this image belong to fragment_letter_list.xml
![screenshot](https://user-images.githubusercontent.com/79671799/109233154-fedeae80-778e-11eb-81a7-e3d126ecbf16.png)

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by jtavva** [comment] 2021-03-18 00:02
Duplicate of #33

**Closed by jtavva** 2021-03-18 00:02 UTC
Labels: duplicate
