### ISSUE TITLE
Android Basics: Fragments Navigation component

### ISSUE THREAD

**Issue by hectoreve** [google-developer-training/android-basics-kotlin-words-app#210] opened 2021-11-08 18:27 UTC
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-fragments-navigation-component?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-fragments-navigation-component#3

**In which task and step of the codelab can this issue be found?**
Step 4

**Describe the problem**
fragment_letter_list.xml context says    tools:context=".WordListFragment" and should say    tools:context=".LetterListFragment ">

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![image](https://user-images.githubusercontent.com/23179782/140797357-50bbb4b2-bccd-46cf-b058-06a0a1a428d7.png)

**Comment by osuleymanova** [comment] 2021-11-29 23:59
Duplicate of #145, #155, #191

**Comment by osuleymanova** [comment] 2022-10-03 20:06
@hectoreve 
Thank you for reaching out to us. The codelab content was updated:
![Screen Shot 2022-09-30 at 5 08 23 PM](https://user-images.githubusercontent.com/86437155/193668903-e8df2639-3956-4f46-8f9b-99bd549c5ce2.png)

**Comment by osuleymanova** [comment] 2022-10-11 22:30
The ticket was re-opened: it's a localization issue (in Portuguese).

**Closed** 2024-01-11 21:30 UTC
