### ISSUE TITLE
Android Basics: DAC rendering issue Text in codeblock - Collections

### ISSUE THREAD

**Issue by GregBradb** [google-developer-training/android-basics-kotlin-words-app#24] opened 2021-01-03 23:42 UTC
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-collections?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-collections#4

**In which task and step of the codelab can this issue be found?**
Task 5, Step 2

**Describe the problem**
The last paragraph of step 2 appears to have used some sort of HTML code that causes the entire paragraph to show in a single line with a horizontal scroll bar.  The text font is also difficult to read - at least on my screen - due to the light color.

**Steps to reproduce?**
1. Go to...  Codelab 5 (Collections in Kotlin), scroll down to step 2 and look at the appearance of the final paragraph of that step.
2. Click on...
3. See error...

**Versions**
_Android Studio version:_  N/A
_API version of the emulator:_  N/A

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
I am using the Chrome browser
![image](https://user-images.githubusercontent.com/8106705/103491618-327a0980-4dda-11eb-8dbd-9888cbad9326.png)

**Comment by osuleymanova** [comment] 2021-11-29 20:25
The issue is closed as resolved.

**Closed by osuleymanova** 2021-11-29 20:25 UTC
Labels: In progress
